---
- name: Remove any obsolete v4 save script
  file: path=/etc/network/if-post-down.d/iptables-v4 state=absent

- name: Remove any obsolete v4 restore script
  file: path=/etc/network/if-pre-up.d/iptables-v4 state=absent

- name: Remove any obsolete v4 saved rules
  file: path=/etc/iptables.v4.saved state=absent

- name: Install iptables-persistent
  apt: name=iptables-persistent state=present

- name: Check if netfilter-persistent is present
  shell: which netfilter-persistent
  register: is_netfilter
  when: v4_script|changed
  changed_when: false
  ignore_errors: yes

- name: Save v4 rules (netfilter-persistent)
  command: netfilter-persistent save
  when: v4_script|changed and is_netfilter.rc == 0

- name: Save v4 rules (iptables-persistent)
  command: /etc/init.d/iptables-persistent save
  when: v4_script|changed and is_netfilter.rc == 1
